name: wisatabandung
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0-130.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald/Oswald-Regular.ttf

    - family: Nunito_Sans
      fonts:
        - asset: fonts/Nunito_Sans/NunitoSans_10pt-Regular.ttf
